name: Unit Tests
'on':
  workflow_dispatch: {}
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm i
        run: npm i
      - name: npm t
        run: npm t